packaging_format = 2

id = "pyload"
name = "pyLoad"
description.en = "Download Manager"
description.fr = "Gestionnaire de téléchargement"

version = "0.4.20~ynh4"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
website = "https://pyload.net"
admindoc = "https://github.com/pyload/pyload/wiki"
code = "https://github.com/pyload/pyload"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]
    # FIXME : this is a hack, nowhere is it explicitely specific in the systemd conf or app conf that it should run on $port ...
    main.default = 9666

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3-cryptography, python3-pycurl, python3-venv, libcurl4-openssl-dev, libssl-dev, python3-dev"

